.TH l3build 1 "2024-01-09"
.SH NAME
l3build \- Checking and building packages
.SH SYNOPSIS
l3build <target> [<options>] [<names>]
.SH DESCRIPTION
The l3build system is a Lua script for building TeX packages, with particular
emphasis on regression testing. It is written in cross-platform Lua code, so
can be used by any modern TeX distribution with the texlua interpreter. A
package for building with l3build can be written in any TeX dialect; its
defaults are set up for LaTeX packages written in the DocStrip style.
.PP
The standard l3build targets are:
.IP check
Runs all automated tests
.IP clean
Cleans out directory tree
.IP ctan
Creates CTAN-ready archive
.IP doc
Typesets all documentation files
.IP install
Installs files into the local texmf tree
.IP manifest
Creates a manifest file
.IP save
Saves test validation log
.IP tag
Updates release tags in files
.IP uninstall
Uninstalls files from the local texmf tree
.IP unpack
Unpacks the source files into the build tree
.IP upload
Sends archive to CTAN for public release
.SH OPTIONS
Various options apply
.IP --config|-c
Sets the config(s) used for running tests
.IP --date
Sets the date to insert into sources
.IP --debug
Runs target in debug mode
.IP --dirty
Skips cleaning up the test area
.IP --dry-run
Dry run for install or upload
.IP --email
Email address of CTAN uploader
.IP --engine|-e
Sets the engine(s) to use for running test
.IP --epoch
Sets the epoch for tests and typesetting
.IP --file|-F
Takes the upload announcement from the given file
.IP --first
Name of first test to run
.IP --force|-f
Force tests to run if engine is not set up
.IP --full
Installs all files
.IP --halt-on-error|-H
Stops running tests after the first failure
.IP --help|-h
Prints help message and exit
.IP --last
Name of last test to run
.IP --message|-m
Text for upload announcement message
.IP --quiet|-q
Suppresses TeX output when unpacking
.IP --rerun
Skips setup: simply rerun tests
.IP --show-log-on-error
Shows the full log of the failure with 'halt-on-error'
.IP --show-saves|-S
Shows the invocation to update failing .tlg files
.IP --shuffle
Shuffles order of tests
.IP --texmfhome
Location of user texmf tree
.IP --version
Prints version information and exit
.SH BUGS
.SH AUTHOR
The LaTeX Project (latex-team@latex-project.org)
.PP
Please log issues on the GitHub homepage:
https://github.com/latex3/l3build/issues.
.SH SEE ALSO
See l3build.pdf for more details.
