name: Create release

# We create releases for all new tags
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build release
    environment: Release
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v4
      # We need Ghostscript for XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
      # Work around a TL issue
      - run: mtxrun --generate && context --luatex --generate
      - name: Run l3build
        run: texlua l3build.lua ctan -H --show-log-on-error
      # Now create the release (this only runs if the previous steps were successful)
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distrib/ctan/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
